CREATE TABLE posts
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255),
    body VARCHAR(4096),
    rendered_body VARCHAR(4096),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    abstract VARCHAR(4096),
    rendered_abstract VARCHAR(4096)
);
